# Add 'CI' label to any change to CircleCI config and scripts
CI:
  - changed-files:
      any-glob-to-any-file:
        - '.circleci/config.yml'
        - 'ci/**'
        - '.github/**'

# Add 'macros' label to any change to macros
macros:
  - changed-files:
      any-glob-to-any-file:
        - 'macros/**'

# Add 'dbt-core' label to any change to dbt core resources
integration-test:
  - changed-files:
      any-glob-to-any-file:
        - 'integration_tests/**'

# Add 'documentation' label to any change to documentations
documentation:
  - changed-files:
      any-glob-to-any-file:
        - 'README.md'
