name: integration_tests
version: "0.1.0"

profile: integration_tests

config-version: 2
require-dbt-version: [">=0.21.0", "<2.0.0"]

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
