name: TOC Generator
on: push
jobs:
  generateTOC:
    name: TOC Generator
    runs-on: ubuntu-latest
    steps:
      # The GitHub Actions enables us to automatically generate TOC in markdown files.
      # SEE: https://github.com/technote-space/toc-generator
      - uses: technote-space/toc-generator@v2
        with:
          TARGET_PATHS: "README.md"
          TOC_TITLE: ""
          MAX_HEADER_LEVEL: 3
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          COMMIT_MESSAGE: "Generate Table of Contents in markdown files with GitHub Actions"
